### PR TITLE
adds delete link endpoint

### PR DESCRIPTION
**Pull request by gschadegg**
## Summary
Adds Delete endpoint to express/node back end. 
Tested in Postman

'4002' in below endpoint can be either :: process.env.PORT || 4002

Endpoint: http://localhost:4002/api/links/:short

Response is a json message
Kept error messaging similar to other routes

## Checklist
- [ ] fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X ] tested locally.
- [ X] No error nor warning in the console.

[upload the screenshot here] (optional)
**initial GET**
image

**top ID(63398c7ee8c1f06752bfee45) used for DELETE route - reroutes to home**
image

**second GET to confirm ID deleted**
image

### CODE REVIEW

**Comment by cherylli** [comment]
it works perfectly but would like your opinion on a couple of things
- In the other routes i've been using the shortcode to do actions like `PUT http://localhost:4002/api/links/dvprrn`, as the short code should be unique. do you think it's better to use the id like you're doing here? Would like to keep it consistent either way

I think a deletion shouldn't redirect. For example, if we have a list of links for the user, with a delete button or link for each link, we won't want to redirect them back to home after each deletion which will cause the browser to refresh, even if it's the same page. Hope that makes sense. 
image

**Comment by gschadegg** [comment]
> it works perfectly but would like your opinion on a couple of things
> 
> * In the other routes i've been using the shortcode to do actions like `PUT http://localhost:4002/api/links/dvprrn`, as the short code should be unique. do you think it's better to use the id like you're doing here? Would like to keep it consistent either way
> 
> I think a deletion shouldn't redirect. For example, if we have a list of links for the user, with a delete button or link for each link, we won't want to redirect them back to home after each deletion which will cause the browser to refresh, even if it's the same page. Hope that makes sense. image

The redirect could easily change, I wasn't sure if users were going to be able to 'open' a link and had it just in case to be sure that users were back to the main list on being deleted. I can change the response to being a message. I also think in general there should be notifications presented on the FE to communicated that edit/delete etc were successful & error messages.

As long as the url short links have collision avoidance I think using them is the same as creating your own ids essentially and should be fine.

**Comment by cherylli** [comment]
yes frontend will definitely have notifications. 
let's use the short code then, so we don't have to change the old code, and swagger docs

**Comment by cherylli** [comment]
the delete function is gone, maybe during resolve conflicts
https://github.com/webdev-20/TLL-hacktoberfest-2022/blob/65129446b807b26433e0914a41be60fb32894dce/server/src/controllers/links.controller.js

image

**Review by cherylli — APPROVED** [review]
thanks. works perfectly

**Pull request merged**
